# Generated by Django 5.2.5 on 2025-08-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_flightstatuscache'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='passenger_count',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Liczba osób'),
        ),
    ]
