# Generated by Django 5.2.5 on 2025-08-16 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_reservation_passenger_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Czy zakończona'),
        ),
    ]
