# Generated by Django 5.2.5 on 2025-08-16 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='plan',
            field=models.CharField(blank=True, choices=[('small', 'MAŁY PARKING'), ('medium', 'ŚREDNI PARKING'), ('large', 'DUŻY PARKING')], max_length=10, null=True),
        ),
    ]
