# Generated by Django 5.2.5 on 2025-08-16 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_userprofile_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='passenger_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='PricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_1', models.DecimalField(decimal_places=2, default=50.0, max_digits=6)),
                ('day_2', models.DecimalField(decimal_places=2, default=90.0, max_digits=6)),
                ('day_3', models.DecimalField(decimal_places=2, default=130.0, max_digits=6)),
                ('day_4', models.DecimalField(decimal_places=2, default=170.0, max_digits=6)),
                ('day_5', models.DecimalField(decimal_places=2, default=200.0, max_digits=6)),
                ('day_6', models.DecimalField(decimal_places=2, default=230.0, max_digits=6)),
                ('day_7', models.DecimalField(decimal_places=2, default=250.0, max_digits=6)),
                ('extra_day', models.DecimalField(decimal_places=2, default=20.0, max_digits=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
