# Generated by Django 5.2.5 on 2025-08-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_reservation_created_at_reservation_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='plan_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='usage',
            field=models.IntegerField(default=0),
        ),
    ]
